-- Rank4AI Supabase Schema
-- Fresh database for Astro site + Dashboard
-- Based on Lovable export structure

-- ============================================
-- CONTENT TABLES
-- ============================================

CREATE TABLE pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  page_type TEXT DEFAULT 'static',
  role TEXT DEFAULT 'educate',
  state TEXT DEFAULT 'live',
  status TEXT DEFAULT 'live',
  layer TEXT,
  cluster_id TEXT,
  governance_role TEXT,
  governance_notes TEXT,
  meta_title TEXT,
  meta_description TEXT,
  ai_summary TEXT,
  direct_answer TEXT,
  body_content TEXT,
  faq_data JSONB,
  faq_count INTEGER DEFAULT 0,
  include_in_llms BOOLEAN DEFAULT true,
  llms_description TEXT,
  is_flagship BOOLEAN DEFAULT false,
  is_primary_authority BOOLEAN DEFAULT false,
  boundaries_exclusions TEXT,
  intended_ai_queries TEXT,
  youtube_url TEXT,
  spotify_url TEXT,
  medium_url TEXT,
  ebook_url TEXT,
  upward_link TEXT,
  lateral_link TEXT,
  external_reference TEXT,
  is_historical BOOLEAN DEFAULT false,
  historical_reason TEXT,
  successor_page_slug TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_reviewed_at TIMESTAMPTZ
);

CREATE TABLE blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'live',
  governance_layer TEXT,
  governance_cluster TEXT,
  governance_parent_page TEXT,
  governance_page_type TEXT,
  governance_prompt_tier TEXT,
  meta_title TEXT,
  meta_description TEXT,
  primary_question TEXT,
  direct_answer TEXT,
  ai_answer_summary TEXT,
  page_summary TEXT,
  body_content TEXT,
  scenarios_examples TEXT,
  boundaries_exclusions TEXT,
  interpretation_notes TEXT,
  faq_data JSONB,
  faq_count INTEGER DEFAULT 0,
  card_tags TEXT,
  card_excerpt TEXT,
  include_in_llms BOOLEAN DEFAULT true,
  llms_description TEXT,
  internal_role TEXT,
  youtube_url TEXT,
  spotify_url TEXT,
  medium_url TEXT,
  ebook_url TEXT,
  apple_podcast_url TEXT,
  cta_primary_text TEXT,
  cta_secondary_text TEXT,
  cta_secondary_url TEXT,
  auto_generate_schema BOOLEAN DEFAULT true,
  show_date BOOLEAN DEFAULT true,
  show_author BOOLEAN DEFAULT true,
  author TEXT DEFAULT 'Adam Parker',
  has_video BOOLEAN DEFAULT false,
  has_audio BOOLEAN DEFAULT false,
  display_order INTEGER DEFAULT 0,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ai_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT,
  signal_category TEXT,
  status TEXT DEFAULT 'Live',
  priority TEXT,
  meta_title TEXT,
  meta_description TEXT,
  concise_answer TEXT,
  full_answer TEXT,
  schema_enabled BOOLEAN DEFAULT true,
  ai_tested BOOLEAN DEFAULT false,
  needs_review BOOLEAN DEFAULT false,
  parent_service_page TEXT,
  display_on_service_pages TEXT,
  related_blog_slug TEXT,
  youtube_url TEXT,
  spotify_url TEXT,
  podcast_url TEXT,
  podcast_embed_id TEXT,
  apple_podcast_url TEXT,
  github_url TEXT,
  devto_url TEXT,
  wordpress_url TEXT,
  tumblr_url TEXT,
  threads_url TEXT,
  instagram_url TEXT,
  facebook_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_reviewed_at TIMESTAMPTZ
);

CREATE TABLE ai_market_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'live',
  category TEXT,
  stat_value TEXT,
  stat_date TEXT,
  source_name TEXT,
  source_url TEXT,
  summary TEXT,
  body_content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- NOTE: Weekly intelligence is generated by ~/run_weekly_intelligence.py automation
-- It writes directly to this table. The Astro site reads it at build time.
-- The dashboard displays it but does not manage generation.

CREATE TABLE ai_weekly_intelligence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'live',
  publish_date TIMESTAMPTZ,
  top_summary TEXT,
  body_content TEXT,
  card_excerpt TEXT,
  meta_title TEXT,
  meta_description TEXT,
  author TEXT DEFAULT 'Adam Parker',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- ECOSYSTEM TABLES
-- ============================================

CREATE TABLE ecosystem_social_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT DEFAULT 'Social',
  category TEXT,
  description TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ecosystem_distribution_platforms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT DEFAULT 'Distribution',
  category TEXT,
  description TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ecosystem_community_platforms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT DEFAULT 'Community',
  category TEXT,
  description TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- SITE SETTINGS
-- ============================================

CREATE TABLE site_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- CRM TABLES (managed by Dashboard, not Astro site)
-- Dashboard reads/writes these. Astro site only inserts new leads.
-- ============================================

CREATE TABLE conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT,
  email TEXT,
  phone TEXT,
  website_url TEXT,
  message TEXT,
  business_type TEXT,
  source TEXT DEFAULT 'website',
  current_stage TEXT DEFAULT 'new',
  last_activity_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE crm_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID REFERENCES conversations(id),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  due_date TIMESTAMPTZ,
  assigned_to TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID REFERENCES conversations(id),
  action TEXT NOT NULL,
  details TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE llm_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  path TEXT,
  ip_address TEXT,
  user_agent TEXT,
  referer TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- TRIGGERS
-- ============================================

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_pages_updated_at BEFORE UPDATE ON pages FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_blogs_updated_at BEFORE UPDATE ON blog_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_questions_updated_at BEFORE UPDATE ON ai_questions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_stats_updated_at BEFORE UPDATE ON ai_market_stats FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_weekly_updated_at BEFORE UPDATE ON ai_weekly_intelligence FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Validate questions before going Live
CREATE OR REPLACE FUNCTION validate_question_live()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'Live' AND (NEW.concise_answer IS NULL OR NEW.concise_answer = '' OR NEW.meta_title IS NULL OR NEW.meta_title = '') THEN
    RAISE EXCEPTION 'Cannot set status to Live without concise_answer and meta_title';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER validate_ai_question_live BEFORE INSERT OR UPDATE ON ai_questions FOR EACH ROW EXECUTE FUNCTION validate_question_live();

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_pages_slug ON pages(slug);
CREATE INDEX idx_pages_status ON pages(status);
CREATE INDEX idx_blogs_slug ON blog_posts(slug);
CREATE INDEX idx_blogs_status ON blog_posts(status);
CREATE INDEX idx_questions_slug ON ai_questions(slug);
CREATE INDEX idx_questions_status ON ai_questions(status);
CREATE INDEX idx_questions_category ON ai_questions(category);
CREATE INDEX idx_stats_slug ON ai_market_stats(slug);
CREATE INDEX idx_weekly_slug ON ai_weekly_intelligence(slug);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_market_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_weekly_intelligence ENABLE ROW LEVEL SECURITY;
ALTER TABLE ecosystem_social_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ecosystem_distribution_platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE ecosystem_community_platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE llm_requests ENABLE ROW LEVEL SECURITY;

-- Public read for content tables (anon key can read)
CREATE POLICY "Public read pages" ON pages FOR SELECT USING (true);
CREATE POLICY "Public read blogs" ON blog_posts FOR SELECT USING (true);
CREATE POLICY "Public read questions" ON ai_questions FOR SELECT USING (true);
CREATE POLICY "Public read stats" ON ai_market_stats FOR SELECT USING (true);
CREATE POLICY "Public read weekly" ON ai_weekly_intelligence FOR SELECT USING (true);
CREATE POLICY "Public read social" ON ecosystem_social_profiles FOR SELECT USING (true);
CREATE POLICY "Public read distribution" ON ecosystem_distribution_platforms FOR SELECT USING (true);
CREATE POLICY "Public read community" ON ecosystem_community_platforms FOR SELECT USING (true);
CREATE POLICY "Public read settings" ON site_settings FOR SELECT USING (true);

-- Insert for conversations (anon key can submit forms)
CREATE POLICY "Public insert conversations" ON conversations FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert llm_requests" ON llm_requests FOR INSERT WITH CHECK (true);
