// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import partytown from '@astrojs/partytown';

export default defineConfig({
  site: 'https://www.rank4ai.co.uk',
  vite: {
    plugins: [tailwindcss()]
  },
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/admin/') && !page.includes('/lp/'),
    }),
    partytown({
      config: {
        forward: ['dataLayer.push'],
      },
    }),
  ],
  redirects: {
    // Service pages
    '/ai-services': '/what-we-do/',
    '/ai-services/ai-search-audit': '/what-we-do/ai-visibility-audit/',
    '/ai-services/ai-content-rebuild': '/what-we-do/ecosystem-services/',
    '/ai-services/ai-meaning-clean-up': '/what-we-do/full-agency/',
    '/ai-services/ai-messaging-clean-up': '/what-we-do/full-agency/',
    '/ai-services/ai-visibility-boost': '/what-we-do/ecosystem-services/',
    '/ai-services/ai-agency-restructure': '/what-we-do/full-agency/',
    '/ai-services/guides/complete-guide': '/what-we-do/',
    '/ai-visibility-consultancy': '/what-we-do/full-agency/',
    '/ai-search-visibility-services': '/what-we-do/',
    '/ai-seo-audit': '/what-we-do/ai-visibility-audit/',
    '/products': '/what-we-do/',
    '/ai-seo-agency-uk/pricing': '/what-we-do/pricing/',
    '/ai-seo-agency-uk/services': '/what-we-do/',
    // City pages
    '/ai-seo-agency-uk/london': '/who-we-help/london/',
    '/ai-seo-agency-uk/manchester': '/who-we-help/manchester/',
    '/ai-seo-agency-uk/birmingham': '/who-we-help/birmingham/',
    '/ai-seo-agency-uk/leeds': '/who-we-help/leeds/',
    '/ai-seo-agency-uk/bristol': '/who-we-help/bristol/',
    '/ai-seo-agency-uk/essex': '/who-we-help/essex/',
    // Research
    '/ai-market-stats': '/research/uk-ai-visibility-stats/',
    '/ai-search-weekly': '/research/weekly-intelligence/',
    '/methodology': '/research/methodology/',
    '/industry-rankings': '/research/rankings/',
    '/top-10-ai-seo-agencies-uk-2026': '/research/rankings/top-ai-seo-agencies-uk-2026/',
    '/uk-ai-search-specialist-landscape-2026': '/research/rankings/uk-ai-search-specialist-landscape-2026/',
    // Learn
    '/guides': '/learn/guides/',
    '/glossary': '/learn/glossary/',
    '/ai-search-questions': '/learn/questions/',
    '/ai-visibility-check': '/learn/tools/ai-visibility-checker/',
    '/tools/free-llms-txt-creator': '/learn/tools/llms-txt-generator/',
    '/complete-guide-to-ai-search-visibility': '/learn/guides/complete-guide-ai-search/',
    '/guide-to-geo': '/learn/guides/geo/',
    '/how-to-get-cited-chatgpt': '/learn/guides/get-cited-chatgpt/',
    '/ai-search/guides/complete-guide': '/learn/guides/complete-guide-ai-search/',
    '/ai-search/comparisons/guides/complete-guide': '/learn/guides/ai-search-comparisons/',
    '/ai-seo/technical/guides/complete-guide': '/learn/guides/technical-ai-optimisation/',
    '/ai-marketing-growth/guides/complete-guide': '/learn/guides/ai-marketing-growth/',
    '/ai-search-questions/guides/complete-guide': '/learn/questions/',
    '/ai-search/who-should-i-hire': '/learn/guides/who-should-i-hire/',
    // About
    '/how-we-work': '/about/how-we-work/',
    '/our-ai-search-story': '/about/our-story/',
    '/ai-search/framework': '/about/five-signal-framework/',
    '/founder-insights-adam-parker': '/about/',
    '/workingwithus': '/about/how-we-work/',
    '/work-with-an-ai-search-specialist': '/about/how-we-work/',
    // Conversion
    '/start-here': '/free-audit/',
    '/quick-ai-search': '/free-audit/',
    '/rankonchatgpt': '/lp/rank-on-chatgpt/',
    '/ppc': '/lp/rank-on-chatgpt/',
    '/seo-to-aio': '/lp/seo-to-aio/',
    '/meta': '/lp/seo-to-aio/',
    // Old prefix redirects
    '/ai-search-agency-essex': '/who-we-help/essex/',
    '/ai-search-agency-london': '/who-we-help/london/',
    '/ai-search-agency-manchester': '/who-we-help/manchester/',
    '/ai-search-agency-birmingham': '/who-we-help/birmingham/',
    '/ai-search-agency-leeds': '/who-we-help/leeds/',
    '/ai-search-agency-bristol': '/who-we-help/bristol/',
    '/ai-search-services-uk': '/what-we-do/',
    '/ai-search-agency-uk': '/who-we-help/',
    // Question merges (batch 1)
    '/learn/questions/what-should-i-expect-from-an-ai-seo-agency-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/what-is-the-difference-between-an-ai-seo-agency-and-a-normal-seo-agency-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/what-results-should-i-realistically-expect-from-ai-seo-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/how-much-does-it-cost-to-hire-an-ai-seo-agency-in-the-uk-and-what-should-i-expect-to-pay': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/how-much-should-a-uk-business-expect-to-pay-for-proper-ai-search-optimisation-in-2024': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-a-uk-business-expect-to-pay-for-proper-ai-search-optimisation-services': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-i-expect-to-pay-for-proper-ai-search-visibility-work-in-the-uk': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/what-is-the-difference-between-being-cited-and-being-mentioned-by-ai': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/what-s-the-difference-between-getting-cited-by-ai-and-just-being-mentioned-and-why-should-i-care-about-the-distinction': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/what-s-the-difference-between-getting-mentioned-by-ai-and-actually-getting-traffic-from-ai-platforms': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/my-local-business-isn-t-showing-up-in-google-ai-overviews-even-though-i-rank-well-traditionally-what-s-going-wrong': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/why-is-my-business-showing-up-in-chatgpt-but-not-google-ai-overviews': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/why-isn-t-my-business-showing-up-in-google-ai-overviews-when-competitors-are': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/what-happens-if-google-ai-overviews-start-recommending-wrong-information-about-my-business': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/what-happens-to-my-business-if-google-ai-overviews-start-showing-competitor-information-instead-of-mine': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/what-happens-to-my-business-if-google-ai-overviews-starts-showing-incorrect-information-about-my-services': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/how-much-does-proper-ai-search-optimisation-cost-for-a-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-i-budget-for-ai-search-optimisation-for-my-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-a-proper-ai-search-visibility-strategy-cost-for-a-mid-sized-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/what-s-the-difference-between-traditional-seo-agencies-and-ai-search-agencies-in-the-uk': '/learn/questions/what-is-the-difference-between-ai-search-and-traditional-search/',
    '/learn/questions/what-s-the-difference-between-ai-seo-and-traditional-seo-for-uk-businesses': '/learn/questions/what-is-the-difference-between-ai-search-and-traditional-search/',
    '/learn/questions/why-does-chatgpt-mention-my-competitors-instead-of-my-business-when-asked-about-services-i-offer': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-for-the-same-services': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitor-when-i-ask-about-my-industry-but-never-mentions-my-business': '/learn/questions/why-does-chatgpt-recommend-my-competitor-but-not-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-never-mentions-my-business': '/learn/questions/why-does-chatgpt-recommend-my-competitor-but-not-my-business/',
    '/learn/questions/what-happens-to-my-website-traffic-if-chatgpt-starts-recommending-competitors-instead-of-my-business': '/learn/questions/what-happens-if-chatgpt-starts-recommending-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-to-my-business-if-chatgpt-starts-recommending-my-competitors-instead-of-me': '/learn/questions/what-happens-if-chatgpt-starts-recommending-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-and-focus-only-on-traditional-google-seo': '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-optimisation/',
    '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-and-stick-with-traditional-seo': '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-optimisation/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-asked-about-local-services': '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-not-my-business-when-asked-about-our-industry/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-asked-about-services-in-my-area': '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-not-my-business-when-asked-about-our-industry/',
    '/learn/questions/why-does-google-ai-overview-show-my-competitor-instead-of-my-business-when-customers-ask-about-our-services': '/learn/questions/why-does-google-ai-overview-show-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-google-ai-overview-show-my-competitor-instead-of-my-business-when-customers-search-for-what-i-offer': '/learn/questions/why-does-google-ai-overview-show-my-competitors-instead-of-my-business/',
    '/learn/questions/should-i-stop-traditional-seo-and-focus-entirely-on-ai-search-optimisation-for-my-sme': '/learn/questions/should-i-stop-traditional-seo-and-switch-to-ai-search-optimisation/',
    '/learn/questions/should-i-stop-traditional-seo-investment-to-focus-on-ai-search-optimisation-instead': '/learn/questions/should-i-stop-traditional-seo-and-switch-to-ai-search-optimisation/',

    // Question merges (batch 2+3)
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-clients-ask-for-similar-services': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-if-chatgpt-starts-recommending-my-competitors-instead-of-my-business': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-not-my-business-when-asked-about-our-industry': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-i-ask-about-our-industry': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-if-google-ai-overviews-never-mention-my-business': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/what-happens-to-my-business-if-google-ai-overviews-never-mention-my-company': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/how-much-does-it-cost-to-hire-an-ai-seo-agency-in-the-uk-compared-to-traditional-seo': '/learn/questions/how-much-does-ai-seo-cost-compared-to-traditional-seo-for-uk-businesses/',
    '/learn/questions/how-much-does-proper-ai-seo-cost-for-a-small-uk-business-compared-to-traditional-seo': '/learn/questions/how-much-does-ai-seo-cost-compared-to-traditional-seo-for-uk-businesses/',
    '/learn/questions/how-much-does-it-cost-to-get-a-uk-business-visible-in-google-ai-overviews': '/learn/questions/how-much-does-it-cost-to-get-my-business-visible-on-chatgpt-in-the-uk/',
    '/learn/questions/how-much-does-it-cost-to-improve-visibility-in-google-ai-overviews-for-a-uk-business': '/learn/questions/how-much-does-it-cost-to-get-my-business-visible-on-chatgpt-in-the-uk/',
    '/learn/questions/how-do-i-stop-ai-systems-getting-my-business-details-wrong': '/learn/questions/how-do-i-stop-ai-getting-my-business-details-wrong/',
    '/learn/questions/how-do-i-stop-ai-systems-getting-my-business-type-and-services-completely-wrong': '/learn/questions/how-do-i-stop-ai-getting-my-business-details-wrong/',
    '/learn/questions/do-i-need-different-content-strategies-for-each-ai-platform-or-can-i-use-the-same-approach': '/learn/questions/do-i-need-different-content-strategies-for-each-ai-platform/',
    '/learn/questions/do-i-need-different-content-strategies-for-each-ai-platform-or-can-one-approach-work-across-chatgpt-claude-and-perplexity': '/learn/questions/do-i-need-different-content-strategies-for-each-ai-platform/',
    '/learn/questions/do-i-need-a-specialist-ai-seo-agency-or-can-my-current-seo-company-handle-this': '/learn/questions/should-i-replace-my-current-seo-agency-with-an-ai-seo-specialist/',
    '/learn/questions/how-do-i-know-if-an-agency-actually-understands-ai-search-or-if-they-re-just-adding-buzzwords-to-traditional-seo': '/learn/questions/do-i-need-an-ai-seo-agency-or-can-traditional-seo-handle-ai-search/',
    '/learn/questions/should-i-hire-an-ai-seo-agency-or-try-to-handle-chatgpt-and-claude-visibility-improvements-internally-with-my-existing-team': '/learn/questions/should-i-hire-an-ai-seo-agency-or-try-to-manage-ai-search-visibility-internally/',
    '/learn/questions/how-much-should-i-budget-for-ai-seo-services-from-a-uk-agency-and-what-s-actually-included': '/learn/questions/what-does-an-ai-seo-agency-actually-do/',
    '/learn/questions/can-traditional-seo-agencies-actually-deliver-ai-search-results-or-should-i-find-specialists': '/learn/questions/can-traditional-seo-agencies-actually-deliver-proper-ai-search-results-for-uk-businesses/',
    '/learn/questions/should-i-hire-an-ai-seo-agency-or-train-my-existing-marketing-team': '/learn/questions/should-i-hire-an-ai-seo-agency-or-train-my-team-internally/',
    '/learn/questions/can-small-uk-businesses-compete-with-larger-companies-in-ai-search-results': '/learn/questions/can-small-businesses-compete-with-larger-companies-in-ai-search/',
    '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-visibility-completely': '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-optimisation/',
    '/learn/questions/how-long-before-google-ai-overviews-start-affecting-my-website-traffic-in-the-uk': '/learn/questions/should-i-be-worried-about-google-ai-overviews-affecting-my-website-traffic/',
    '/learn/questions/what-happens-if-ai-platforms-start-recommending-my-competitors-instead-of-my-business': '/learn/questions/what-happens-if-ai-systems-start-recommending-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitor-over-my-business-despite-having-better-reviews': '/learn/questions/why-does-chatgpt-recommend-my-competitor-but-not-my-business/',
    '/learn/questions/why-does-my-business-appear-differently-across-chatgpt-and-google-ai-overviews': '/learn/questions/why-does-my-business-appear-in-chatgpt-but-not-google-ai-overviews/',
    '/learn/questions/why-is-my-business-appearing-incorrectly-in-google-ai-overviews-and-how-do-i-fix-it': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews-when-competitors-are/',
    '/learn/questions/why-isn-t-my-business-appearing-in-google-ai-overviews-when-competitors-are': '/learn/questions/why-is-my-competitor-appearing-in-google-ai-overviews-but-my-business-isn-t/',
    '/learn/questions/what-happens-if-google-ai-overviews-start-showing-my-competitors-for-queries-about-my-specific-company-name': '/learn/questions/what-happens-if-google-ai-overviews-start-showing-incorrect-information-about-my-company/',
    '/learn/questions/what-s-the-difference-between-getting-featured-in-google-ai-overviews-versus-traditional-search-results': '/learn/questions/what-is-the-difference-between-ai-search-and-traditional-search/',
    '/learn/questions/why-do-ai-tools-give-different-business-recommendations-in-the-uk': '/learn/questions/how-do-i-get-my-business-recommended-by-ai-tools-in-the-uk/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-when-i-search-for-services-we-both-offer': '/learn/questions/why-does-chatgpt-recommend-my-competitors-when-i-ask-about-services-we-both-offer/',
    '/learn/questions/can-ai-search-optimisation-replace-traditional-seo-for-uk-businesses': '/learn/questions/how-much-does-ai-search-optimisation-cost-for-uk-businesses/',
    '/learn/questions/how-much-does-proper-ai-search-visibility-cost-compared-to-traditional-seo-work': '/learn/questions/will-my-traditional-seo-work-hurt-my-ai-search-visibility/',
    '/learn/questions/how-much-does-ai-search-optimisation-cost-compared-to-traditional-seo': '/learn/questions/how-much-does-ai-seo-cost-compared-to-traditional-seo-in-the-uk/',
    '/learn/questions/how-much-should-a-proper-ai-seo-audit-cost-for-a-mid-sized-uk-business': '/learn/questions/how-much-does-proper-ai-seo-cost-for-a-uk-small-business/',
    '/learn/questions/how-much-should-i-budget-for-ai-search-visibility-services-in-the-uk': '/learn/questions/how-much-should-uk-smes-budget-for-ai-search-visibility-services/',
    '/learn/questions/why-do-ai-search-results-keep-getting-my-business-details-wrong-and-how-can-i-fix-this': '/learn/questions/is-ai-getting-my-business-information-wrong-and-how-do-i-fix-it/',
  },
});
