// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import partytown from '@astrojs/partytown';

export default defineConfig({
  site: 'https://www.rank4ai.co.uk',
  vite: {
    plugins: [tailwindcss()]
  },
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/admin/') && !page.includes('/lp/'),
    }),
    partytown({
      config: {
        forward: ['dataLayer.push'],
      },
    }),
  ],
  redirects: {
    // Service pages
    '/ai-services': '/what-we-do/',
    '/ai-services/ai-search-audit': '/what-we-do/ai-visibility-audit/',
    '/ai-services/ai-content-rebuild': '/what-we-do/ecosystem-services/',
    '/ai-services/ai-meaning-clean-up': '/what-we-do/full-agency/',
    '/ai-services/ai-messaging-clean-up': '/what-we-do/full-agency/',
    '/ai-services/ai-visibility-boost': '/what-we-do/ecosystem-services/',
    '/ai-services/ai-agency-restructure': '/what-we-do/full-agency/',
    '/ai-services/guides/complete-guide': '/what-we-do/',
    '/ai-visibility-consultancy': '/what-we-do/full-agency/',
    '/ai-search-visibility-services': '/what-we-do/',
    '/ai-seo-audit': '/what-we-do/ai-visibility-audit/',
    '/products': '/what-we-do/',
    '/ai-seo-agency-uk/pricing': '/what-we-do/pricing/',
    '/ai-seo-agency-uk/services': '/what-we-do/',
    // City pages
    '/ai-seo-agency-uk/london': '/who-we-help/london/',
    '/ai-seo-agency-uk/manchester': '/who-we-help/manchester/',
    '/ai-seo-agency-uk/birmingham': '/who-we-help/birmingham/',
    '/ai-seo-agency-uk/leeds': '/who-we-help/leeds/',
    '/ai-seo-agency-uk/bristol': '/who-we-help/bristol/',
    '/ai-seo-agency-uk/essex': '/who-we-help/essex/',
    // Research
    '/ai-market-stats': '/research/uk-ai-visibility-stats/',
    '/ai-search-weekly': '/research/weekly-intelligence/',
    '/methodology': '/research/methodology/',
    '/industry-rankings': '/research/rankings/',
    '/top-10-ai-seo-agencies-uk-2026': '/research/rankings/top-ai-seo-agencies-uk-2026/',
    '/uk-ai-search-specialist-landscape-2026': '/research/rankings/uk-ai-search-specialist-landscape-2026/',
    // Learn
    '/guides': '/learn/guides/',
    '/glossary': '/learn/glossary/',
    '/ai-search-questions': '/learn/questions/',
    '/ai-visibility-check': '/learn/tools/ai-visibility-checker/',
    '/tools/free-llms-txt-creator': '/learn/tools/llms-txt-generator/',
    '/complete-guide-to-ai-search-visibility': '/learn/guides/complete-guide-ai-search/',
    '/guide-to-geo': '/learn/guides/geo/',
    '/how-to-get-cited-chatgpt': '/learn/guides/get-cited-chatgpt/',
    '/ai-search/guides/complete-guide': '/learn/guides/complete-guide-ai-search/',
    '/ai-search/comparisons/guides/complete-guide': '/learn/guides/ai-search-comparisons/',
    '/ai-seo/technical/guides/complete-guide': '/learn/guides/technical-ai-optimisation/',
    '/ai-marketing-growth/guides/complete-guide': '/learn/guides/ai-marketing-growth/',
    '/ai-search-questions/guides/complete-guide': '/learn/questions/',
    '/ai-search/who-should-i-hire': '/learn/guides/who-should-i-hire/',
    // About
    '/how-we-work': '/about/how-we-work/',
    '/our-ai-search-story': '/about/our-story/',
    '/ai-search/framework': '/about/five-signal-framework/',
    '/founder-insights-adam-parker': '/about/',
    '/workingwithus': '/about/how-we-work/',
    '/work-with-an-ai-search-specialist': '/about/how-we-work/',
    // Conversion
    '/start-here': '/free-audit/',
    '/quick-ai-search': '/free-audit/',
    '/rankonchatgpt': '/lp/rank-on-chatgpt/',
    '/ppc': '/lp/rank-on-chatgpt/',
    '/seo-to-aio': '/lp/seo-to-aio/',
    '/meta': '/lp/seo-to-aio/',
    // Old prefix redirects
    '/ai-search-agency-essex': '/who-we-help/essex/',
    '/ai-search-agency-london': '/who-we-help/london/',
    '/ai-search-agency-manchester': '/who-we-help/manchester/',
    '/ai-search-agency-birmingham': '/who-we-help/birmingham/',
    '/ai-search-agency-leeds': '/who-we-help/leeds/',
    '/ai-search-agency-bristol': '/who-we-help/bristol/',
    '/ai-search-services-uk': '/what-we-do/',
    '/ai-search-agency-uk': '/who-we-help/',
    // Question merges (batch 1)
    '/learn/questions/what-should-i-expect-from-an-ai-seo-agency-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/what-is-the-difference-between-an-ai-seo-agency-and-a-normal-seo-agency-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/what-results-should-i-realistically-expect-from-ai-seo-in-the-uk': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/how-much-does-it-cost-to-hire-an-ai-seo-agency-in-the-uk-and-what-should-i-expect-to-pay': '/learn/questions/how-do-i-choose-the-right-ai-seo-agency-in-the-uk/',
    '/learn/questions/how-much-should-a-uk-business-expect-to-pay-for-proper-ai-search-optimisation-in-2024': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-a-uk-business-expect-to-pay-for-proper-ai-search-optimisation-services': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-i-expect-to-pay-for-proper-ai-search-visibility-work-in-the-uk': '/learn/questions/how-much-should-i-expect-to-pay-for-ai-search-optimisation/',
    '/learn/questions/what-is-the-difference-between-being-cited-and-being-mentioned-by-ai': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/what-s-the-difference-between-getting-cited-by-ai-and-just-being-mentioned-and-why-should-i-care-about-the-distinction': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/what-s-the-difference-between-getting-mentioned-by-ai-and-actually-getting-traffic-from-ai-platforms': '/learn/questions/what-s-the-difference-between-being-mentioned-and-cited-by-ai/',
    '/learn/questions/my-local-business-isn-t-showing-up-in-google-ai-overviews-even-though-i-rank-well-traditionally-what-s-going-wrong': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/why-is-my-business-showing-up-in-chatgpt-but-not-google-ai-overviews': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/why-isn-t-my-business-showing-up-in-google-ai-overviews-when-competitors-are': '/learn/questions/why-is-my-business-not-appearing-in-google-ai-overviews/',
    '/learn/questions/what-happens-if-google-ai-overviews-start-recommending-wrong-information-about-my-business': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/what-happens-to-my-business-if-google-ai-overviews-start-showing-competitor-information-instead-of-mine': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/what-happens-to-my-business-if-google-ai-overviews-starts-showing-incorrect-information-about-my-services': '/learn/questions/what-happens-if-google-ai-overviews-get-my-business-information-wrong/',
    '/learn/questions/how-much-does-proper-ai-search-optimisation-cost-for-a-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-i-budget-for-ai-search-optimisation-for-my-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/how-much-should-a-proper-ai-search-visibility-strategy-cost-for-a-mid-sized-uk-business': '/learn/questions/how-much-should-a-uk-business-budget-for-ai-search-optimisation/',
    '/learn/questions/what-s-the-difference-between-traditional-seo-agencies-and-ai-search-agencies-in-the-uk': '/learn/questions/what-is-the-difference-between-ai-search-and-traditional-search/',
    '/learn/questions/what-s-the-difference-between-ai-seo-and-traditional-seo-for-uk-businesses': '/learn/questions/what-is-the-difference-between-ai-search-and-traditional-search/',
    '/learn/questions/why-does-chatgpt-mention-my-competitors-instead-of-my-business-when-asked-about-services-i-offer': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-for-the-same-services': '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitor-when-i-ask-about-my-industry-but-never-mentions-my-business': '/learn/questions/why-does-chatgpt-recommend-my-competitor-but-not-my-business/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-never-mentions-my-business': '/learn/questions/why-does-chatgpt-recommend-my-competitor-but-not-my-business/',
    '/learn/questions/what-happens-to-my-website-traffic-if-chatgpt-starts-recommending-competitors-instead-of-my-business': '/learn/questions/what-happens-if-chatgpt-starts-recommending-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-to-my-business-if-chatgpt-starts-recommending-my-competitors-instead-of-me': '/learn/questions/what-happens-if-chatgpt-starts-recommending-my-competitors-instead-of-my-business/',
    '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-and-focus-only-on-traditional-google-seo': '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-optimisation/',
    '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-and-stick-with-traditional-seo': '/learn/questions/what-happens-to-my-business-if-i-ignore-ai-search-optimisation/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-asked-about-local-services': '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-not-my-business-when-asked-about-our-industry/',
    '/learn/questions/why-does-chatgpt-recommend-my-competitors-instead-of-my-business-when-asked-about-services-in-my-area': '/learn/questions/why-does-chatgpt-recommend-my-competitors-but-not-my-business-when-asked-about-our-industry/',
    '/learn/questions/why-does-google-ai-overview-show-my-competitor-instead-of-my-business-when-customers-ask-about-our-services': '/learn/questions/why-does-google-ai-overview-show-my-competitors-instead-of-my-business/',
    '/learn/questions/why-does-google-ai-overview-show-my-competitor-instead-of-my-business-when-customers-search-for-what-i-offer': '/learn/questions/why-does-google-ai-overview-show-my-competitors-instead-of-my-business/',
    '/learn/questions/should-i-stop-traditional-seo-and-focus-entirely-on-ai-search-optimisation-for-my-sme': '/learn/questions/should-i-stop-traditional-seo-and-switch-to-ai-search-optimisation/',
    '/learn/questions/should-i-stop-traditional-seo-investment-to-focus-on-ai-search-optimisation-instead': '/learn/questions/should-i-stop-traditional-seo-and-switch-to-ai-search-optimisation/',
  },
});
